# re-enable a specific script via `package.json:dependenciesMeta:<moduleName>:built = true`
enableScripts: false

# Don't install anything that was released less than a week ago
npmMinimalAgeGate: "1w"

approvedGitRepositories:
  - "https://github.com/yarnpkg/*"
  - "ssh://git@github.com/yarnpkg/*"

# ------------------------------------------------------------------------------

compressionLevel: mixed
enableGlobalCache: false
nodeLinker: node-modules
